name: Main
on:
  pull_request:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: webiny/action-conventional-commits@v1.3.0

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: dmd

      - name: Run tests
        run: dub test
  release:
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: runner.os == 'Linux'
        run: |
          echo "ASSET_NAME=iex-parser_${{ format('{0}_{1}_{2}.tar.gz', github.ref_name, runner.os, runner.arch) }}" >> "$GITHUB_ENV"

      - if: runner.os == 'Windows'
        run: |
          echo "ASSET_NAME=iex-parser_${{ format('{0}_{1}_{2}.zip', github.ref_name, runner.os, runner.arch) }}" >> "$env:GITHUB_ENV"

      - uses: actions/checkout@v4

      - uses: webiny/action-conventional-commits@v1.3.0

      - name: Get current version
        id: current_version
        run: |
          echo "version=$(cat .VERSION)" >> $GITHUB_OUTPUT

      - name: Update version
        run: |
          echo "${{ github.ref_name }}" > .VERSION

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc

      - name: Create release binary
        run: dub build --build=release

      - name: Package - Linux
        if: runner.os == 'Linux'
        run: tar -zcvf $ASSET_NAME iex-parser

      - name: Package - Windows
        if: runner.os == 'Windows'
        run: Compress-Archive -Path iex-parser.exe -Destination $env:ASSET_NAME

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                    "title": "## Feature",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## Fix",
                    "labels": ["fix", "bug"]
                },
                {
                    "title": "## Other",
                    "labels": []
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ]
            }
          fromTag: ${{ steps.current_version.version }}
          toTag: ${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          files: ${{ env.ASSET_NAME }}
